AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  warehouse-api

  Sample SAM Template for warehouse-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  WarehouseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: warehouse
      AttributeDefinitions:
        - AttributeName: ShipmentID
          AttributeType: S
      KeySchema:
        - AttributeName: ShipmentID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ShipperTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: shipper
      AttributeDefinitions:
        - AttributeName: ShipperID
          AttributeType: S
      KeySchema:
        - AttributeName: ShipperID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  WarehouseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: warehouse/
      Handler: app.app
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WarehouseTable
      Events:
        Test:
          Type: Api
          Properties:
            Path: /
            Method: get
        ListItems:
          Type: Api
          Properties:
            Path: /items
            Method: get
        PutItems:
          Type: Api
          Properties:
            Path: /items
            Method: post
        GetShipper:
          Type: Api
          Properties:
            Path: /shippers
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WarehouseApi:
    Description: API Gateway endpoint URL for Prod stage for warehouse function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  WarehouseFunction:
    Description: warehouse Lambda Function ARN
    Value: !GetAtt WarehouseFunction.Arn
  WarehouseFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt WarehouseFunctionRole.Arn
